In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

import pandas as pd

from src.data.market_loader import MarketLoader

from src.term_structure.bootstrap_curve import bootstrap_df_from_sofr, build_zero_curve_from_df

In [2]:
# downloading market curves
loader = MarketLoader()
curves = loader.loader_pipeline()

# get sofr curve
sofr_curve = curves['sofr']
sofr_curve

treasury curve dataset already downloaded..
sofr curve dataset already downloaded..
money_market curve dataset already downloaded..

              ON  FEDFUNDS
Date
2018-05-01  1.76      1.70
2018-05-02  1.75      1.70
2018-05-03  1.74      1.70
2018-05-04  1.72      1.70
2018-05-07  1.71      1.70
...          ...       ...
2026-04-06  3.65      3.64
2026-04-07  3.62      3.64
2026-04-08  3.59      3.64
2026-04-09  3.57      3.64
2026-04-10  3.61      3.64

[2074 rows x 2 columns]

In [3]:
# bootstrapping discount factors from sofr curve
df_bootstrap = bootstrap_df_from_sofr(
    sofr_curve = sofr_curve
)

df_bootstrap

                  ON
2018-05-01  0.999951
2018-05-02  0.999951
2018-05-03  0.999952
2018-05-04  0.999952
2018-05-07  0.999953
...              ...
2026-04-06  0.999899
2026-04-07  0.999899
2026-04-08  0.999900
2026-04-09  0.999901
2026-04-10  0.999900

[2074 rows x 1 columns]

In [4]:
# constructing zero curve from discount curve
zero_curve = build_zero_curve_from_df(
    discount_curve = df_bootstrap
)

zero_curve

                  ON
2018-05-01  1.759957
2018-05-02  1.749957
2018-05-03  1.739958
2018-05-04  1.719959
2018-05-07  1.709959
...              ...
2026-04-06  3.649815
2026-04-07  3.619818
2026-04-08  3.589821
2026-04-09  3.569823
2026-04-10  3.609819

[2074 rows x 1 columns]